### ISSUE TITLE
Add support for displaying iperf udp results

### ISSUE THREAD

**Issue by gberche-orange** [markormesher/iperf-prometheus-collector#26]
iperf supports both tcp and udp, and produce for each kind of tests different json reports.

Currently, the iperf-prometheus-collector assumes json report format used by tcp tests.

**Comment by markormesher** [comment]
Happy to add UDP support and update the metrics that are produced as a result. As with the other issue, I'll review your PR for this after I get the repo back into a more current state.

**Comment by markormesher** [comment]
Addressed in the re-write: https://github.com/markormesher/iperf-prometheus-collector/pull/35/files#diff-25b6a03dc5ae75da7c7a52fd357d63fff0b1e563a5b66a3a862684013c922e8cR36-R39
