### ISSUE TITLE
new counters iperf_tests_started and iperf_tests_completed

### ISSUE THREAD

**Issue by gberche-orange** [markormesher/iperf-prometheus-collector#28]
As a user,
given test duration (say 10s) might smaller than scrape time (1 min by default),
in order to get approx time interval at which a test is running (as to detect concurrent tests when multiple instance of the exporter are running),
I need new counters `iperf_tests_started` and `iperf_tests_completed`

`(iperf_tests_completed - iperf_tests_started)` would display concurrent tests running. For multiple exporters `sum(iperf_tests_completed - iperf_tests_started)` would also display concurrent tests running

**Comment by markormesher** [comment]
Addressed in the re-write: https://github.com/markormesher/iperf-prometheus-collector/pull/35/files#diff-c444f711e9191b53952edb65bfd8c644419fc7695c62611dc0fb304b4fb197d6R9-R13
