### ISSUE TITLE
Add HELP and TYPE strings

### ISSUE THREAD

**Issue by gberche-orange** [markormesher/iperf-prometheus-collector#29]
As a user
in order to get tooltips on iperf exporter metrics
I need HELP string to be produced by the /metrics endpoint

https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information

https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example
> \# HELP http_requests_total The total number of HTTP requests.
> \# TYPE http_requests_total counter
> http_requests_total{method="post",code="200"} 1027 1395066363000
> 

https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md#metricfamily-1 also adds UNIT, I'm not sure this is used in prometheus/grafana UIs
> \# TYPE foo_seconds counter
> \# UNIT foo_seconds seconds
> \# HELP foo_seconds Some text and \n some \" escaping

**Comment by markormesher** [comment]
Addressed in the re-write: https://github.com/markormesher/iperf-prometheus-collector/pull/35/files#diff-51ebf883f5eb8e0662695474e1cb1f752f3ac6d8e1c5f46c5666eb0563560387R8-R34
